from __future__ import annotations

SEED_LISTINGS = {
    "morceau": [
        {
            "source_listing_url": "https://www.morceau.ca/products/relay-screen-by-kathy-stanton-for-herman-miller",
            "title": "Relay screen by Kathy Stanton for Herman Miller",
            "price_raw": "$1,400.00 CAD",
            "price_value": 1400.0,
            "currency": "CAD",
            "primary_image_url": "https://cdn.shopify.com/s/files/1/0000/0001/files/morceau-relay-screen.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "international",
            "ships_to_montreal": 1,
            "shipping_note": "International shipping available on all items.",
            "category": "bookshelves / wall units",
            "designer": "Kathy Stanton",
            "maker": "Herman Miller",
            "materials": "painted wood, divider screen",
            "dimensions_text": "",
            "condition_text": "Vintage item curated by Morceau.",
            "source_description": "Vintage divider screen from Morceau's vintage collection.",
            "location_text": "Montreal, QC",
            "era": "",
        },
        {
            "source_listing_url": "https://www.morceau.ca/products/eames-psc-side-chair-by-charles-ray-eames-for-herman-miller",
            "title": "Eames PSC side chair by Charles & Ray Eames for Herman Miller",
            "price_raw": "$450.00 CAD",
            "price_value": 450.0,
            "currency": "CAD",
            "primary_image_url": "https://cdn.shopify.com/s/files/1/0000/0001/files/morceau-eames-chair.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "international",
            "ships_to_montreal": 1,
            "shipping_note": "International shipping available on all items.",
            "category": "dining chairs",
            "designer": "Charles & Ray Eames",
            "maker": "Herman Miller",
            "materials": "molded shell, metal base",
            "dimensions_text": "",
            "condition_text": "Vintage side chair.",
            "source_description": "Shell chair from Morceau's vintage collection.",
            "location_text": "Montreal, QC",
            "era": "",
        },
    ],
    "showroom-montreal": [
        {
            "source_listing_url": "https://www.showroommtl.com/biblio",
            "title": "Unite murale en teck '60s modele CADO par Poul Cadovius",
            "price_raw": "Contactez nous pour les details",
            "price_value": None,
            "currency": "CAD",
            "primary_image_url": "https://static.wixstatic.com/media/fc24cc_da90cc3192de41f8a5bf6f86c7badb30~mv2.jpg/v1/fill/w_250,h_250,al_c,q_90,enc_auto/fc24cc_da90cc3192de41f8a5bf6f86c7badb30~mv2.jpg",
            "additional_image_urls": [],
            "availability_status": "unknown",
            "shipping_scope": "quote_required",
            "ships_to_montreal": 1,
            "shipping_note": "Price requires direct contact with the shop.",
            "category": "bookshelves / wall units",
            "designer": "Poul Cadovius",
            "maker": "",
            "materials": "teak",
            "dimensions_text": "126 in L x 16 in D x 80 in H",
            "condition_text": "Restauree",
            "source_description": "Large teak wall unit from Showroom Montreal's nouveautes page.",
            "location_text": "Montreal, QC",
            "era": "1960s",
        },
        {
            "source_listing_url": "https://www.showroommtl.com/nouveaute?lightbox=dataItem-mmz4dux33",
            "title": "Lampe en verre et aluminium '60s modele Dream Island par RAAK",
            "price_raw": "750 $",
            "price_value": 750.0,
            "currency": "CAD",
            "primary_image_url": "https://static.wixstatic.com/media/fc24cc_3c6f1680fc2b438fa7d793e695070210~mv2.jpg/v1/fill/w_250,h_250,al_c,q_90,enc_auto/fc24cc_3c6f1680fc2b438fa7d793e695070210~mv2.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "local_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal local source.",
            "category": "lighting",
            "designer": "",
            "maker": "RAAK",
            "materials": "glass, aluminum",
            "dimensions_text": "13 in D x 17 in H",
            "condition_text": "",
            "source_description": "Vintage lamp listed on Showroom Montreal's nouveautes page.",
            "location_text": "Montreal, QC",
            "era": "1960s",
        },
        {
            "source_listing_url": "https://www.showroommtl.com/sofa",
            "title": "Sofa en cerisier '60s modele 118 par Grete Jalk",
            "price_raw": "2150 $",
            "price_value": 2150.0,
            "currency": "CAD",
            "primary_image_url": "https://static.wixstatic.com/media/fc24cc_d9d7f0ccb8aa44d3a90528690affd6f8~mv2.jpg/v1/fill/w_250,h_250,al_c,q_90,enc_auto/fc24cc_d9d7f0ccb8aa44d3a90528690affd6f8~mv2.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "local_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal local source.",
            "category": "sofas",
            "designer": "Grete Jalk",
            "maker": "",
            "materials": "cherry wood, upholstery",
            "dimensions_text": "71 in L x 28.5 in D x 31.5 in H",
            "condition_text": "Restored, new upholstery in Sherpa.",
            "source_description": "Cherry sofa listed on Showroom Montreal's nouveautes page.",
            "location_text": "Montreal, QC",
            "era": "1960s",
        },
    ],
    "montreal-moderne": [
        {
            "source_listing_url": "https://www.montrealmoderne.com/nouveaut%C3%A9s#tabouret-en-teck",
            "title": "Tabouret en teck",
            "price_raw": "Prix 595,00C$",
            "price_value": 595.0,
            "currency": "CAD",
            "primary_image_url": "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1200&q=80",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "local_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal local source.",
            "category": "dining chairs",
            "designer": "",
            "maker": "",
            "materials": "teak",
            "dimensions_text": "",
            "condition_text": "",
            "source_description": "Fresh listing from Montreal Moderne nouveautes.",
            "location_text": "Montreal, QC",
            "era": "",
        },
        {
            "source_listing_url": "https://www.montrealmoderne.com/nouveaut%C3%A9s#table-a-manger-en-teck",
            "title": "Table a manger en teck",
            "price_raw": "Prix 1 245,00C$",
            "price_value": 1245.0,
            "currency": "CAD",
            "primary_image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "local_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal local source.",
            "category": "dining tables",
            "designer": "",
            "maker": "",
            "materials": "teak",
            "dimensions_text": "",
            "condition_text": "",
            "source_description": "Teak dining table from Montreal Moderne nouveautes.",
            "location_text": "Montreal, QC",
            "era": "",
        },
        {
            "source_listing_url": "https://www.montrealmoderne.com/nouveaut%C3%A9s#buffet-en-teck",
            "title": "Buffet en teck",
            "price_raw": "Prix 1 145,00C$",
            "price_value": 1145.0,
            "currency": "CAD",
            "primary_image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "local_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal local source.",
            "category": "sideboards / credenzas",
            "designer": "",
            "maker": "",
            "materials": "teak",
            "dimensions_text": "",
            "condition_text": "",
            "source_description": "Teak buffet from Montreal Moderne nouveautes.",
            "location_text": "Montreal, QC",
            "era": "",
        },
    ],
    "green-wall-vintage": [
        {
            "source_listing_url": "https://www.greenwallvintage.ca/products/mid-century-teak-sideboard",
            "title": "Mid Century Teak Sideboard",
            "price_raw": "$995.00",
            "price_value": 995.0,
            "currency": "CAD",
            "primary_image_url": "https://www.greenwallvintage.ca/cdn/shop/files/teak-sideboard.jpg",
            "additional_image_urls": [],
            "availability_status": "sold_out",
            "shipping_scope": "canada_us",
            "ships_to_montreal": 1,
            "shipping_note": "Delivery across Canada and the United States.",
            "category": "sideboards / credenzas",
            "designer": "",
            "maker": "",
            "materials": "teak",
            "dimensions_text": "48 in W x 16.5 in D x 34.5 in H",
            "condition_text": "Professionally restored.",
            "source_description": "Mid-century teak sideboard with delivery across Canada and the United States.",
            "location_text": "Ottawa, ON",
            "era": "",
        },
        {
            "source_listing_url": "https://www.greenwallvintage.ca/products/mid-century-solid-teak-dresser",
            "title": "Mid Century Solid Teak Dresser",
            "price_raw": "$1,795.00",
            "price_value": 1795.0,
            "currency": "CAD",
            "primary_image_url": "https://www.greenwallvintage.ca/cdn/shop/files/solid-teak-dresser.jpg",
            "additional_image_urls": [],
            "availability_status": "sold_out",
            "shipping_scope": "canada_us",
            "ships_to_montreal": 1,
            "shipping_note": "Delivery across Canada and the United States.",
            "category": "dressers / commodes",
            "designer": "",
            "maker": "Imperial Furniture of Canada",
            "materials": "teak",
            "dimensions_text": "66 in L x 18 in D x 29 in H",
            "condition_text": "Professionally restored.",
            "source_description": "Solid teak dresser from Green Wall Vintage.",
            "location_text": "Ottawa, ON",
            "era": "",
        },
    ],
    "vintage-home-boutique": [
        {
            "source_listing_url": "https://vintagehomeboutique.ca/products/erik-ole-jorgensen-for-tarm-stole-mid-century-teak-armchairs",
            "title": "Erik Ole Jorgensen for Tarm Stole Mid-Century Teak Armchairs",
            "price_raw": "$2,495.00",
            "price_value": 2495.0,
            "currency": "CAD",
            "primary_image_url": "https://vintagehomeboutique.ca/cdn/shop/files/erik-ole-jorgensen-armchairs.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "canada",
            "ships_to_montreal": 1,
            "shipping_note": "Canada-wide shipping available.",
            "category": "lounge chairs",
            "designer": "Erik Ole Jorgensen",
            "maker": "Tarm Stole",
            "materials": "teak, upholstery",
            "dimensions_text": "",
            "condition_text": "Restored.",
            "source_description": "Designer armchairs from Vintage Home Boutique.",
            "location_text": "Toronto, ON",
            "era": "",
        },
        {
            "source_listing_url": "https://vintagehomeboutique.ca/products/danish-mid-century-modern-teak-bedside-chests",
            "title": "Danish Mid-Century Modern Teak Bedside Chests",
            "price_raw": "$1,495.00",
            "price_value": 1495.0,
            "currency": "CAD",
            "primary_image_url": "https://vintagehomeboutique.ca/cdn/shop/files/teak-bedside-chests.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "canada",
            "ships_to_montreal": 1,
            "shipping_note": "Canada-wide shipping available.",
            "category": "nightstands",
            "designer": "",
            "maker": "",
            "materials": "teak",
            "dimensions_text": "",
            "condition_text": "Restored.",
            "source_description": "Teak bedside chests from Vintage Home Boutique.",
            "location_text": "Toronto, ON",
            "era": "",
        },
    ],
    "le-centerpiece": [
        {
            "source_listing_url": "https://lecenterpiece.com/products/wardrobe-by-willy-van-der-meeren-for-tubax",
            "title": "Wardrobe by Willy Van Der Meeren for Tubax",
            "price_raw": "$5,200.00 CAD",
            "price_value": 5200.0,
            "currency": "CAD",
            "primary_image_url": "https://lecenterpiece.com/cdn/shop/files/willy-van-der-meeren-wardrobe.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "worldwide_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal to worldwide; oversized items may require a shipping quote.",
            "category": "dressers / commodes",
            "designer": "Willy Van Der Meeren",
            "maker": "Tubax",
            "materials": "painted metal, storage cabinet",
            "dimensions_text": "",
            "condition_text": "",
            "source_description": "Premium vintage wardrobe from Le Centerpiece.",
            "location_text": "Montreal, QC",
            "era": "",
        },
        {
            "source_listing_url": "https://lecenterpiece.com/products/coffee-table-on-wheels-by-gae-aulenti-for-fontana-arte",
            "title": "Coffee Table on Wheels by Gae Aulenti for Fontana Arte",
            "price_raw": "$2,500.00 CAD",
            "price_value": 2500.0,
            "currency": "CAD",
            "primary_image_url": "https://lecenterpiece.com/cdn/shop/files/gae-aulenti-coffee-table.jpg",
            "additional_image_urls": [],
            "availability_status": "available",
            "shipping_scope": "worldwide_quote",
            "ships_to_montreal": 1,
            "shipping_note": "Montreal to worldwide; oversized items may require a shipping quote.",
            "category": "coffee tables",
            "designer": "Gae Aulenti",
            "maker": "Fontana Arte",
            "materials": "glass, chrome",
            "dimensions_text": "",
            "condition_text": "",
            "source_description": "Iconic coffee table from Le Centerpiece's new additions.",
            "location_text": "Montreal, QC",
            "era": "",
        },
    ],
}
