from __future__ import annotations

from .source_types import SourceDefinition

SOURCE_DEFINITIONS = [
    SourceDefinition(
        slug="morceau",
        name="Morceau",
        website="https://www.morceau.ca/",
        wordmark_text="morceau",
        wordmark_style="lowercase",
        street_address="4812 rue Saint-Urbain",
        city="Montreal",
        province="QC",
        postal_code="H2T 2W2",
        country="Canada",
        latitude=45.5225,
        longitude=-73.5956,
        public_location_note="",
        is_montreal_local=True,
        shipping_summary="International shipping available on all items.",
        source_type="direct_shop",
        crawl_priority=1,
        notes="Strong Shopify-style vintage collection.",
        description="Montreal-based vintage and design shop with a strong MCM furniture mix.",
        style_focus="Vintage, Scandinavian, Italian, collectible design.",
        listing_urls=("https://www.morceau.ca/collections/vintage",),
        parser="shopify_collection",
    ),
    SourceDefinition(
        slug="showroom-montreal",
        name="Showroom Montreal",
        website="https://www.showroommtl.com/",
        wordmark_text="SHOWROOM MONTRÉAL",
        wordmark_style="wide_caps",
        street_address="3987 rue Sainte-Catherine Est",
        city="Montreal",
        province="QC",
        postal_code="H1W 2G7",
        country="Canada",
        latitude=45.5436,
        longitude=-73.5441,
        public_location_note="Street address comes from public business listings; the source site currently emphasizes phone/email contact.",
        is_montreal_local=True,
        shipping_summary="Montreal local source; some items require direct contact for price or shipping.",
        source_type="direct_shop",
        crawl_priority=1,
        notes="Wix-style nouveautes page with detailed text listings.",
        description="Local Montreal MCM specialist focused on restored Scandinavian and Canadian modern furniture.",
        style_focus="Scandinavian, Danish, restored vintage, teak and rosewood.",
        listing_urls=(
            "https://www.showroommtl.com/nouveaute",
            "https://www.showroommtl.com/buffet",
            "https://www.showroommtl.com/table",
            "https://www.showroommtl.com/chaises",
            "https://www.showroommtl.com/sofa",
            "https://www.showroommtl.com/fauteuil",
            "https://www.showroommtl.com/tables-dappoints",
            "https://www.showroommtl.com/bureau",
            "https://www.showroommtl.com/biblio",
            "https://www.showroommtl.com/lits-commodes",
            "https://www.showroommtl.com/luminaire",
            "https://www.showroommtl.com/deco",
        ),
        parser="showroom",
    ),
    SourceDefinition(
        slug="montreal-moderne",
        name="Montreal Moderne",
        website="https://www.montrealmoderne.com/",
        wordmark_text="MONTRÉAL MØDERNE",
        wordmark_style="wide_caps",
        street_address="3894 rue Sainte-Catherine Est",
        city="Montreal",
        province="QC",
        postal_code="H1W 2G4",
        country="Canada",
        latitude=45.5435,
        longitude=-73.5447,
        public_location_note="",
        is_montreal_local=True,
        shipping_summary="Montreal local source with sold-out states visible on-page.",
        source_type="direct_shop",
        crawl_priority=1,
        notes="Wix-style nouveautes page with clear price or sold-out text.",
        description="Montreal Scandinavian and MCM furniture specialist established in 2007.",
        style_focus="Scandinavian comfort, teak furniture, clean Danish-inspired pieces.",
        listing_urls=(
            "https://www.montrealmoderne.com/nouveaut%C3%A9s",
            "https://www.montrealmoderne.com/salon",
            "https://www.montrealmoderne.com/salle-%C3%A0-manger",
            "https://www.montrealmoderne.com/chambre",
        ),
        parser="montreal_moderne",
    ),
    SourceDefinition(
        slug="le-centerpiece",
        name="Le Centerpiece",
        website="https://lecenterpiece.com/",
        wordmark_text="Centerpiece",
        wordmark_style="title",
        street_address="6250 rue Hutchison, #305",
        city="Montreal",
        province="QC",
        postal_code="H2V 4C5",
        country="Canada",
        latitude=45.5268,
        longitude=-73.6075,
        public_location_note="",
        is_montreal_local=True,
        shipping_summary="Montreal to worldwide; oversized items may require a shipping quote.",
        source_type="direct_shop",
        crawl_priority=1,
        notes="Curated premium vintage inventory with quote-based shipping for large pieces.",
        description="Premium Montreal design gallery with collectible furniture and decorative objects.",
        style_focus="Collectible design, premium vintage furniture, European modernism.",
        listing_urls=(
            "https://lecenterpiece.com/collections/furniture",
            "https://lecenterpiece.com/collections/chairs",
            "https://lecenterpiece.com/collections/storage",
            "https://lecenterpiece.com/collections/kitchen-dining",
            "https://lecenterpiece.com/collections/living-room",
            "https://lecenterpiece.com/collections/office",
            "https://lecenterpiece.com/collections/usm-modular-furniture",
        ),
        parser="shopify_collection",
    ),
    SourceDefinition(
        slug="maison-singulier",
        name="Maison Singulier",
        website="https://maisonsingulier.com/",
        wordmark_text="maison singulier",
        wordmark_style="lowercase",
        street_address="6545 rue Durocher, #308",
        city="Montreal",
        province="QC",
        postal_code="H2V 3Z4",
        country="Canada",
        latitude=45.5266,
        longitude=-73.6082,
        public_location_note="Visits are appointment-based.",
        is_montreal_local=True,
        shipping_summary="Montreal local source; large items may require a shipping quote.",
        source_type="direct_shop",
        crawl_priority=2,
        notes="Shopify collections with live furniture inventory; archive collections are excluded.",
        description="Montreal-based vintage furniture and home goods shop focused on modernist and mid-century design.",
        style_focus="Modernist, Brazilian, Mid-Century, Postmodern, collectible furniture.",
        listing_urls=(
            "https://maisonsingulier.com/collections/seating",
            "https://maisonsingulier.com/collections/tables",
            "https://maisonsingulier.com/collections/storage",
            "https://maisonsingulier.com/collections/lighting",
        ),
        parser="shopify_collection",
    ),
    SourceDefinition(
        slug="yardsale-vintage",
        name="Yardsale Vintage",
        website="https://yardsale-vintage.com/",
        wordmark_text="Yardsale Vintage",
        wordmark_style="title",
        street_address="",
        city="Montreal",
        province="QC",
        postal_code="",
        country="Canada",
        latitude=None,
        longitude=None,
        public_location_note="No public street address found; contact the shop for pickup or appointment details.",
        is_montreal_local=True,
        shipping_summary="Montreal local pickup; shipping is available to Canada and the United States by quote.",
        source_type="direct_shop",
        crawl_priority=2,
        notes="Cargo gallery; current Shop gallery is parsed and Archive gallery is excluded.",
        description="Montreal studio focused on restored one-of-a-kind vintage furniture.",
        style_focus="Restored vintage furniture, designer seating, MCM case goods.",
        listing_urls=("https://yardsale-vintage.com/",),
        parser="cargo_gallery",
    ),
    SourceDefinition(
        slug="chez-lamothe",
        name="Chez Lamothe",
        website="https://www.chezlamothe.com/",
        wordmark_text="CHEZ LAMOTHE",
        wordmark_style="wide_caps",
        street_address="7211 rue Alexandra",
        city="Montreal",
        province="QC",
        postal_code="H2R 2X2",
        country="Canada",
        latitude=45.5382,
        longitude=-73.6221,
        public_location_note="",
        is_montreal_local=True,
        shipping_summary="Montreal local source; delivery in Montreal and regional shipping by quote.",
        source_type="direct_shop",
        crawl_priority=2,
        notes="Square Online storefront API; product data includes prices, images, descriptions, and out-of-stock badges.",
        description="Montreal shop specializing in restored mid-century furniture, especially teak and Scandinavian pieces.",
        style_focus="Restored Mid-Century, teak, Scandinavian, Danish and Canadian furniture.",
        listing_urls=(
            "https://cdn5.editmysite.com/app/store/api/v28/editor/users/131647755/sites/345976907244501379/products",
        ),
        parser="square_storefront",
    ),
    SourceDefinition(
        slug="habitat-mobilier",
        name="Habitat Mobilier",
        website="https://habitatmobilier.com/",
        wordmark_text="habitat",
        wordmark_style="lowercase",
        street_address="1108 chemin de Knowlton",
        city="West Brome",
        province="QC",
        postal_code="J0E 2P0",
        country="Canada",
        latitude=45.2104,
        longitude=-72.6567,
        public_location_note="",
        is_montreal_local=False,
        shipping_summary="Eastern Townships source; delivery available in greater Montreal and across Quebec.",
        source_type="direct_shop",
        crawl_priority=3,
        notes="Squarespace store; only in-stock product rows are treated as current public inventory.",
        description="West Brome shop focused on restored Scandinavian and mid-century vintage furniture.",
        style_focus="Restored Scandinavian, Danish, teak, rosewood, walnut, mid-century furniture.",
        listing_urls=("https://habitatmobilier.com/boutique",),
        parser="squarespace_store",
    ),
    SourceDefinition(
        slug="green-wall-vintage",
        name="Green Wall Vintage",
        website="https://www.greenwallvintage.ca/",
        wordmark_text="Green Wall Vintage",
        wordmark_style="title",
        street_address="5712 Frank Kenny Road",
        city="Ottawa",
        province="ON",
        postal_code="K0A 3H0",
        country="Canada",
        latitude=45.4322,
        longitude=-75.4141,
        public_location_note="",
        is_montreal_local=False,
        shipping_summary="Ottawa regional source with delivery available across Canada and the United States.",
        source_type="direct_shop",
        crawl_priority=3,
        notes="Shopify inventory with visible prices and stock states; non-furniture products are filtered.",
        description="Ottawa-area vintage shop with a strong mid-century modern furniture catalogue.",
        style_focus="Mid-century modern, Danish-inspired, teak, walnut, rosewood furniture.",
        listing_urls=("https://www.greenwallvintage.ca/collections/all",),
        parser="shopify_collection",
    ),
    SourceDefinition(
        slug="mostly-danish",
        name="Mostly Danish",
        website="https://mostlydanish.com/",
        wordmark_text="MOSTLY DANISH",
        wordmark_style="wide_caps",
        street_address="5429 Farran's Point Road",
        city="Ingleside",
        province="ON",
        postal_code="K0C 1M0",
        country="Canada",
        latitude=44.9954,
        longitude=-75.0042,
        public_location_note="Mostly Danish also lists a Wellington location; this source is currently modeled as the Ingleside shop.",
        is_montreal_local=False,
        shipping_summary="Regional Montreal-Ottawa corridor source; pickup or delivery by quote.",
        source_type="direct_shop",
        crawl_priority=3,
        notes="Shopify furniture collections only; outdoor, Oriental, accents, and archive collections are excluded.",
        description="Regional Scandinavian furniture source with Danish and teak vintage inventory.",
        style_focus="Danish, Scandinavian, teak, rosewood, seating, tables, sideboards, storage.",
        listing_urls=(
            "https://mostlydanish.com/collections/wm-seating",
            "https://mostlydanish.com/collections/wm-tables",
            "https://mostlydanish.com/collections/wm-sideboards",
            "https://mostlydanish.com/collections/wm-storage",
            "https://mostlydanish.com/collections/wm-office",
        ),
        parser="shopify_collection",
    ),
]
